# Site settings
title: Hausarzt in Löhne - Praxis Dr. Biesenbaum & Dr. Gerbaulet
description: "Hausarzt für Allgemeinmedizin in Löhne (OWL). Gemeinschaftspraxis Dr. Jens Biesenbaum und Dr. Uwe Gerbaulet"
baseurl: /homepage # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: svg/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Dr. med. Jens Biesenbaum<br>Dr. med. Uwe Gerbaulet
    hero_description: Gemeinschaftspraxis für Allgemeinmedizin in Löhne (Ostwestfalen)

# Infobox
infobox:
    titel1: Aktuelle Informationen
    text1: Corona, Abweichende Öffnungszeiten, etc. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perspiciatis nostrum ab vero temporibus magnam, delectus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perspiciatis nostrum ab vero temporibus magnam, delectus!
    icon1: bolt
    titel2: Jetzt geht's ab in den Urlaub
    text2: Vom 1. bis 31. sind wir leider nicht in der Praxis, sondern im Urlaub. Yippieyayeah!
    icon2: ambulance
    titel3: Urlaubsvertretung
    text3: Dr. Peppa Pig
    icon3: calendar


# Contact info
contact:
    phone: 05731 81482
    fax: 05731 81482
    emergency: 116117
    email: contact@hausarzt-loehne.de
    address: Goethestraße 1-3
    city: 32584 Löhne
    google_maps: https://goo.gl/maps/iKjxJctEiZvcNLdVA

# Opening hours
monday: 7:30 - 12:00 | 15:00 - 18:00
tuesday: 7:30 - 12:00 | 15:00 - 18:00
wednesday: 7:30 - 13:00
thursday: 7:30 - 12:00 | 16:00 - 18:00
friday: 7:30 - 12:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Social settings
# facebook: http://facebook.com
# twitter: http://twitter.com
# instagram: http://instagram.com
# youtube: http://youtube.com
# skype: skype:obaez_design?userinfo
# feed: yes

# Footer
copyright: Impressum | Datenschutz | Cookie-Richtlinie

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
